import type { Metadata } from "next";
import "@/styles/globals.scss";
import styles from "./layout.module.scss";
import Header from "@/components/main/Header/Header";
import Footer from "@/components/main/Footer/Footer";

export const metadata: Metadata = {
  title: "Main",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={styles.main_body}>
        <Header />

        <main className={styles.main_content_block}>{children}</main>

        <Footer />
      </body>
    </html>
  );
}
